name: manage-azure-policy-df28f83f
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/AppService_append_sites_with_minimum_TLS_version_to_enforce._Append-AppService-latestTLS/**'
#      - 'policies/AppService_append_enable_https_only_setting_to_enforce_https_setting._Append-AppService-httpsonly/**'
#      - 'policies/Web_Application_should_only_be_accessible_over_HTTPS_Deny-AppServiceWebApp-http/**'
#      - 'policies/Function_App_should_only_be_accessible_over_HTTPS_Deny-AppServiceFunctionApp-http/**'
#      - 'policies/API_App_should_only_be_accessible_over_HTTPS_Deny-AppServiceApiApp-http/**'
#      - 'policies/Limit_allowed_vm_sizes_for_Azure_Machine_Learning_compute_clusters_and_compute_instances_Deny-MachineLearning-Compute-VmSize/**'
#      - 'policies/Enforce_scale_settings_for_Azure_Machine_Learning_compute_clusters_Deny-MachineLearning-ComputeCluster-Scale/**'
#      - 'policies/Deny_the_creation_of_private_DNS_Deny-Private-DNS-Zones/**'
#      - 'policies/Deny_the_creation_of_public_IP_Deny-PublicIP/**'
#      - 'policies/RDP_access_from_the_Internet_should_be_blocked_Deny-RDP-From-Internet/**'
#      - 'policies/Azure_SQL_Database_should_have_the_minimal_TLS_version_set_to_the_highest_version_Deny-Sql-minTLS/**'
#      - 'policies/SQL_Managed_Instance_should_have_the_minimal_TLS_version_set_to_the_highest_version_Deny-SqlMi-minTLS/**'
#      - 'policies/Storage_Account_set_to_minimum_TLS_and_Secure_transfer_should_be_enabled_Deny-Storage-minTLS/**'
#      - 'policies/Subnets_should_have_a_Network_Security_Group_Deny-Subnet-Without-Nsg/**'
#      - 'policies/Deny_vNet_peering_to_non-approved_vNets_Deny-VNET-Peering-To-Non-Approved-VNETs/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_API_Management_to_Log_Analytics_workspace_Deploy-Diagnostics-APIMgmt/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Analysis_Services_to_Log_Analytics_workspace_Deploy-Diagnostics-AnalysisService/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Container_Instances_to_Log_Analytics_workspace_Deploy-Diagnostics-ACI/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Container_Registry_to_Log_Analytics_workspace_Deploy-Diagnostics-ACR/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Data_Lake_Analytics_to_Log_Analytics_workspace_Deploy-Diagnostics-DLAnalytics/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Azure_Function_App_to_Log_Analytics_workspace_Deploy-Diagnostics-Function/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_IoT_Hub_to_Log_Analytics_workspace_Deploy-Diagnostics-iotHub/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Load_Balancer_to_Log_Analytics_workspace_Deploy-Diagnostics-LoadBalancer/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_App_Service_Plan_to_Log_Analytics_workspace_Deploy-Diagnostics-WebServerFarm/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_App_Service_to_Log_Analytics_workspace_Deploy-Diagnostics-Website/**'
#      - 'policies/Deploys_NSG_flow_logs_and_traffic_analytics_Deploy-Nsg-FlowLogs/**'
#      - 'policies/Deploys_NSG_flow_logs_and_traffic_analytics_to_Log_Analytics_Deploy-Nsg-FlowLogs-to-LA/**'
#      - 'policies/Deploy_SQL_database_auditing_settings_Deploy-Sql-AuditingSettings/**'
#      - 'policies/SQL_servers_deploys_a_specific_min_TLS_version_requirement._Deploy-SQL-minTLS/**'
#      - 'policies/Deploy_SQL_Database_security_Alert_Policies_configuration_with_email_admin_accounts_Deploy-Sql-SecurityAlertPolicies/**'
#      - 'policies/Deploy_SQL_Database_Transparent_Data_Encryption_Deploy-Sql-Tde/**'
#      - 'policies/Deploy_SQL_Database_vulnerability_Assessments_Deploy-Sql-vulnerabilityAssessments/**'
#      - 'policies/Azure_Storage_deploy_a_specific_min_TLS_version_requirement_and_enforce_SSL/HTTPS_Deploy-Storage-sslEnforcement/**'
#      - 'policies/SQL_managed_instances_deploy_a_specific_min_TLS_version_requirement._Deploy-SqlMi-minTLS/**'
#      - 'policies/Deploy_Virtual_Network_with_peering_to_the_hub_Deploy-VNET-HubSpoke/**'
#      - 'initiatives/Public_network_access_should_be_disabled_for_PaaS_services_Deny-PublicPaaSEndpoints/**'
#      - 'initiatives/Deploy_Diagnostic_Settings_to_Azure_Services_Deploy-Diagnostics-LogAnalytics/**'
#      - 'initiatives/Deploy_SQL_Database_built-in_SQL_security_configuration_Deploy-Sql-Security/**'
#      - 'policies/Azure_Backup_should_be_enabled_for_Virtual_Machines_013e242c-8828-4970-87b3-ab247555486d/**'
#      - 'policies/Shared_dashboards_should_not_have_markdown_tiles_with_inline_content_04c655fe-0ac7-48ae-9a32-3a2e208c7624/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Service_Bus_to_Log_Analytics_workspace_04d53d87-841c-4f23-8a5b-21564380b55e/**'
#      - 'policies/Resource_logs_in_Azure_Data_Lake_Store_should_be_enabled_057ef27e-665e-4328-8ea3-04b3122bd9fb/**'
#      - 'policies/CORS_should_not_allow_every_resource_to_access_your_Function_Apps_0820b7b9-23aa-4725-a1ce-ae4558f718e5/**'
#      - 'policies/Configure_backup_on_virtual_machines_without_a_given_tag_to_an_existing_recovery_services_vault_in_the_same_location_09ce66bc-1220-4153-8104-e3f51c936913/**'
#      - 'policies/SQL_servers_should_use_customer-managed_keys_to_encrypt_data_at_rest_0a370ff3-6cab-4e85-8995-295fd854c5b8/**'
#      - 'policies/Managed_identity_should_be_used_in_your_Function_App_0da106f2-4ca3-48e8-bc85-c638fe6aea8f/**'
#      - 'policies/Remote_debugging_should_be_turned_off_for_Function_Apps_0e60b895-3786-45da-8377-9c6b4b6ac5f9/**'
#      - 'policies/_Preview_Recovery_Services_vaults_should_use_private_link_11e3da8c-1d68-4392-badd-0ff3c43ab5b0/**'
#      - 'policies/Transparent_Data_Encryption_on_SQL_databases_should_be_enabled_17k78e20-9358-41c9-923c-fb736d382a12/**'
#      - 'policies/Public_network_access_on_Azure_SQL_Database_should_be_disabled_1b8ca024-1d5c-4dec-8995-b1a932b41780/**'
#      - 'policies/Vulnerability_assessment_should_be_enabled_on_SQL_Managed_Instance_1b7aa243-30e4-4c9e-bca8-d0d3022b634a/**'
#      - 'policies/Key_vaults_should_have_soft_delete_enabled_1e66c121-a66a-4b1f-9b83-0fd99bf0fc2d/**'
#      - 'policies/Configure_SQL_servers_to_have_auditing_enabled_to_Log_Analytics_workspace_25da7dfb-0666-4a15-a8f5-402127efd8bb/**'
#      - 'policies/Append_a_tag_and_its_value_to_resources_2a0e14a6-b0a6-4fab-991a-187a4f81c498/**'
#      - 'policies/Configure_backup_on_virtual_machines_with_a_given_tag_to_an_existing_recovery_services_vault_in_the_same_location_345fa903-145c-4fe1-8bcd-93ec2adccde8/**'
#      - 'policies/FTPS_only_should_be_required_in_your_Function_App_399b2637-a50f-4f95-96f8-3a145476eb15/**'
#      - 'policies/An_activity_log_alert_should_exist_for_specific_Security_operations_3b980d31-7904-4bb7-8575-5665739a8052/**'
#      - 'policies/Deploy_-_Configure_Dependency_agent_to_be_enabled_on_Windows_virtual_machine_scale_sets_3be22e3b-d919-47aa-805e-8985dbeb0ad9/**'
#      - 'policies/Append_a_tag_and_its_value_to_resource_groups_49c88fc8-6fd1-46fd-a676-f12d1d3a4c71/**'
#      - 'policies/Add_a_tag_to_resources_4f9dc7db-30c1-420c-b61a-e1d640128d26/**'
#      - 'policies/App_Service_should_use_private_link_687aa49d-0982-40f8-bf6b-66d1da97a04b/**'
#      - 'policies/Add_a_tag_to_resource_groups_726aca4c-86e9-4b04-b0c5-073027359532/**'
#      - 'policies/Storage_accounts_should_be_limited_by_allowed_SKUs_7433c107-6db4-4ad1-b57a-a76dce0154a1/**'
#      - 'policies/_Preview_Configure_Azure_Recovery_Services_vaults_to_use_private_DNS_zones_942bd215-1a66-44be-af65-6a1c0318dbe2/**'
#      - 'policies/_Preview_Configure_blob_backup_for_all_storage_accounts_that_do_not_contain_a_given_tag_to_a_backup_vault_in_the_same_region_958dbd4e-0e20-4385-a082-d3f20c2a6ad8/**'
#      - 'policies/Require_a_tag_on_resource_groups_96670d01-0a4d-4649-9c89-2d3abc0a5025/**'
#      - 'policies/Add_a_tag_to_subscriptions_96d9a89c-0d67-41fc-899d-2b9599f76a24/**'
#      - 'policies/Append_a_tag_and_its_value_from_the_resource_group_9ea02ca2-71db-412d-8b00-7c7ca9fcd32d/**'
#      - 'policies/Audit_usage_of_custom_RBAC_rules_a451c1ef-c6ca-483d-87ed-f49761e3ffb5/**'
#      - 'policies/Inherit_a_tag_from_the_resource_group_cd3aa116-8754-49c9-a813-ad46512ece54/**'
#      - 'policies/Add_or_replace_a_tag_on_resource_groups_d157c373-a6c4-483d-aaad-570756956268/**'
#      - 'policies/Long-term_geo-redundant_backup_should_be_enabled_for_Azure_SQL_Databases_d38fc420-0735-4ef3-ac11-c806f651a570/**'
#      - 'policies/Configure_SQL_servers_to_have_auditing_enabled_f4c68484-132f-41f9-9b6d-3e4b1cb55036/**'
#      - 'policies/External_accounts_with_owner_permissions_should_be_removed_from_your_subscription_f8456c1c-aa66-4dfb-861a-25d127b775c9/**'
#      - 'policies/Secrets_should_have_content_type_set_75262d3e-ba4a-4f43-85f8-9f72c090e5e3/**'
#      - 'initiatives/Audit_Public_Network_Access_f1535064-3294-48fa-94e2-6e83095a5c08/**'
#      - 'initiatives/Deploy_Windows_Azure_Monitor_Agent_with_user-assigned_managed_identity-based_auth_and_associate_with_Data_Collection_Rule_0d1b56c6-6d1f-4a5d-8695-b15efbea6b49/**'
#      - .github/workflows/manage-azure-policy-df28f83f.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_df28f83f}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/AppService_append_sites_with_minimum_TLS_version_to_enforce._Append-AppService-latestTLS/**
          policies/AppService_append_enable_https_only_setting_to_enforce_https_setting._Append-AppService-httpsonly/**
          policies/Web_Application_should_only_be_accessible_over_HTTPS_Deny-AppServiceWebApp-http/**
          policies/Function_App_should_only_be_accessible_over_HTTPS_Deny-AppServiceFunctionApp-http/**
          policies/API_App_should_only_be_accessible_over_HTTPS_Deny-AppServiceApiApp-http/**
          policies/Limit_allowed_vm_sizes_for_Azure_Machine_Learning_compute_clusters_and_compute_instances_Deny-MachineLearning-Compute-VmSize/**
          policies/Enforce_scale_settings_for_Azure_Machine_Learning_compute_clusters_Deny-MachineLearning-ComputeCluster-Scale/**
          policies/Deny_the_creation_of_private_DNS_Deny-Private-DNS-Zones/**
          policies/Deny_the_creation_of_public_IP_Deny-PublicIP/**
          policies/RDP_access_from_the_Internet_should_be_blocked_Deny-RDP-From-Internet/**
          policies/Azure_SQL_Database_should_have_the_minimal_TLS_version_set_to_the_highest_version_Deny-Sql-minTLS/**
          policies/SQL_Managed_Instance_should_have_the_minimal_TLS_version_set_to_the_highest_version_Deny-SqlMi-minTLS/**
          policies/Storage_Account_set_to_minimum_TLS_and_Secure_transfer_should_be_enabled_Deny-Storage-minTLS/**
          policies/Subnets_should_have_a_Network_Security_Group_Deny-Subnet-Without-Nsg/**
          policies/Deny_vNet_peering_to_non-approved_vNets_Deny-VNET-Peering-To-Non-Approved-VNETs/**
          policies/Deploy_Diagnostic_Settings_for_API_Management_to_Log_Analytics_workspace_Deploy-Diagnostics-APIMgmt/**
          policies/Deploy_Diagnostic_Settings_for_Analysis_Services_to_Log_Analytics_workspace_Deploy-Diagnostics-AnalysisService/**
          policies/Deploy_Diagnostic_Settings_for_Container_Instances_to_Log_Analytics_workspace_Deploy-Diagnostics-ACI/**
          policies/Deploy_Diagnostic_Settings_for_Container_Registry_to_Log_Analytics_workspace_Deploy-Diagnostics-ACR/**
          policies/Deploy_Diagnostic_Settings_for_Data_Lake_Analytics_to_Log_Analytics_workspace_Deploy-Diagnostics-DLAnalytics/**
          policies/Deploy_Diagnostic_Settings_for_Azure_Function_App_to_Log_Analytics_workspace_Deploy-Diagnostics-Function/**
          policies/Deploy_Diagnostic_Settings_for_IoT_Hub_to_Log_Analytics_workspace_Deploy-Diagnostics-iotHub/**
          policies/Deploy_Diagnostic_Settings_for_Load_Balancer_to_Log_Analytics_workspace_Deploy-Diagnostics-LoadBalancer/**
          policies/Deploy_Diagnostic_Settings_for_App_Service_Plan_to_Log_Analytics_workspace_Deploy-Diagnostics-WebServerFarm/**
          policies/Deploy_Diagnostic_Settings_for_App_Service_to_Log_Analytics_workspace_Deploy-Diagnostics-Website/**
          policies/Deploys_NSG_flow_logs_and_traffic_analytics_Deploy-Nsg-FlowLogs/**
          policies/Deploys_NSG_flow_logs_and_traffic_analytics_to_Log_Analytics_Deploy-Nsg-FlowLogs-to-LA/**
          policies/Deploy_SQL_database_auditing_settings_Deploy-Sql-AuditingSettings/**
          policies/SQL_servers_deploys_a_specific_min_TLS_version_requirement._Deploy-SQL-minTLS/**
          policies/Deploy_SQL_Database_security_Alert_Policies_configuration_with_email_admin_accounts_Deploy-Sql-SecurityAlertPolicies/**
          policies/Deploy_SQL_Database_Transparent_Data_Encryption_Deploy-Sql-Tde/**
          policies/Deploy_SQL_Database_vulnerability_Assessments_Deploy-Sql-vulnerabilityAssessments/**
          policies/Azure_Storage_deploy_a_specific_min_TLS_version_requirement_and_enforce_SSL/HTTPS_Deploy-Storage-sslEnforcement/**
          policies/SQL_managed_instances_deploy_a_specific_min_TLS_version_requirement._Deploy-SqlMi-minTLS/**
          policies/Deploy_Virtual_Network_with_peering_to_the_hub_Deploy-VNET-HubSpoke/**
          initiatives/Public_network_access_should_be_disabled_for_PaaS_services_Deny-PublicPaaSEndpoints/**
          initiatives/Deploy_Diagnostic_Settings_to_Azure_Services_Deploy-Diagnostics-LogAnalytics/**
          initiatives/Deploy_SQL_Database_built-in_SQL_security_configuration_Deploy-Sql-Security/**
          policies/Azure_Backup_should_be_enabled_for_Virtual_Machines_013e242c-8828-4970-87b3-ab247555486d/**
          policies/Shared_dashboards_should_not_have_markdown_tiles_with_inline_content_04c655fe-0ac7-48ae-9a32-3a2e208c7624/**
          policies/Deploy_Diagnostic_Settings_for_Service_Bus_to_Log_Analytics_workspace_04d53d87-841c-4f23-8a5b-21564380b55e/**
          policies/Resource_logs_in_Azure_Data_Lake_Store_should_be_enabled_057ef27e-665e-4328-8ea3-04b3122bd9fb/**
          policies/CORS_should_not_allow_every_resource_to_access_your_Function_Apps_0820b7b9-23aa-4725-a1ce-ae4558f718e5/**
          policies/Configure_backup_on_virtual_machines_without_a_given_tag_to_an_existing_recovery_services_vault_in_the_same_location_09ce66bc-1220-4153-8104-e3f51c936913/**
          policies/SQL_servers_should_use_customer-managed_keys_to_encrypt_data_at_rest_0a370ff3-6cab-4e85-8995-295fd854c5b8/**
          policies/Managed_identity_should_be_used_in_your_Function_App_0da106f2-4ca3-48e8-bc85-c638fe6aea8f/**
          policies/Remote_debugging_should_be_turned_off_for_Function_Apps_0e60b895-3786-45da-8377-9c6b4b6ac5f9/**
          policies/_Preview_Recovery_Services_vaults_should_use_private_link_11e3da8c-1d68-4392-badd-0ff3c43ab5b0/**
          policies/Transparent_Data_Encryption_on_SQL_databases_should_be_enabled_17k78e20-9358-41c9-923c-fb736d382a12/**
          policies/Public_network_access_on_Azure_SQL_Database_should_be_disabled_1b8ca024-1d5c-4dec-8995-b1a932b41780/**
          policies/Vulnerability_assessment_should_be_enabled_on_SQL_Managed_Instance_1b7aa243-30e4-4c9e-bca8-d0d3022b634a/**
          policies/Key_vaults_should_have_soft_delete_enabled_1e66c121-a66a-4b1f-9b83-0fd99bf0fc2d/**
          policies/Configure_SQL_servers_to_have_auditing_enabled_to_Log_Analytics_workspace_25da7dfb-0666-4a15-a8f5-402127efd8bb/**
          policies/Append_a_tag_and_its_value_to_resources_2a0e14a6-b0a6-4fab-991a-187a4f81c498/**
          policies/Configure_backup_on_virtual_machines_with_a_given_tag_to_an_existing_recovery_services_vault_in_the_same_location_345fa903-145c-4fe1-8bcd-93ec2adccde8/**
          policies/FTPS_only_should_be_required_in_your_Function_App_399b2637-a50f-4f95-96f8-3a145476eb15/**
          policies/An_activity_log_alert_should_exist_for_specific_Security_operations_3b980d31-7904-4bb7-8575-5665739a8052/**
          policies/Deploy_-_Configure_Dependency_agent_to_be_enabled_on_Windows_virtual_machine_scale_sets_3be22e3b-d919-47aa-805e-8985dbeb0ad9/**
          policies/Append_a_tag_and_its_value_to_resource_groups_49c88fc8-6fd1-46fd-a676-f12d1d3a4c71/**
          policies/Add_a_tag_to_resources_4f9dc7db-30c1-420c-b61a-e1d640128d26/**
          policies/App_Service_should_use_private_link_687aa49d-0982-40f8-bf6b-66d1da97a04b/**
          policies/Add_a_tag_to_resource_groups_726aca4c-86e9-4b04-b0c5-073027359532/**
          policies/Storage_accounts_should_be_limited_by_allowed_SKUs_7433c107-6db4-4ad1-b57a-a76dce0154a1/**
          policies/_Preview_Configure_Azure_Recovery_Services_vaults_to_use_private_DNS_zones_942bd215-1a66-44be-af65-6a1c0318dbe2/**
          policies/_Preview_Configure_blob_backup_for_all_storage_accounts_that_do_not_contain_a_given_tag_to_a_backup_vault_in_the_same_region_958dbd4e-0e20-4385-a082-d3f20c2a6ad8/**
          policies/Require_a_tag_on_resource_groups_96670d01-0a4d-4649-9c89-2d3abc0a5025/**
          policies/Add_a_tag_to_subscriptions_96d9a89c-0d67-41fc-899d-2b9599f76a24/**
          policies/Append_a_tag_and_its_value_from_the_resource_group_9ea02ca2-71db-412d-8b00-7c7ca9fcd32d/**
          policies/Audit_usage_of_custom_RBAC_rules_a451c1ef-c6ca-483d-87ed-f49761e3ffb5/**
          policies/Inherit_a_tag_from_the_resource_group_cd3aa116-8754-49c9-a813-ad46512ece54/**
          policies/Add_or_replace_a_tag_on_resource_groups_d157c373-a6c4-483d-aaad-570756956268/**
          policies/Long-term_geo-redundant_backup_should_be_enabled_for_Azure_SQL_Databases_d38fc420-0735-4ef3-ac11-c806f651a570/**
          policies/Configure_SQL_servers_to_have_auditing_enabled_f4c68484-132f-41f9-9b6d-3e4b1cb55036/**
          policies/External_accounts_with_owner_permissions_should_be_removed_from_your_subscription_f8456c1c-aa66-4dfb-861a-25d127b775c9/**
          policies/Secrets_should_have_content_type_set_75262d3e-ba4a-4f43-85f8-9f72c090e5e3/**
          initiatives/Audit_Public_Network_Access_f1535064-3294-48fa-94e2-6e83095a5c08/**
          initiatives/Deploy_Windows_Azure_Monitor_Agent_with_user-assigned_managed_identity-based_auth_and_associate_with_Data_Collection_Rule_0d1b56c6-6d1f-4a5d-8695-b15efbea6b49/**
